namespace: claudie
resources:
- crd
- ns.yaml
- operator.yaml
- context-box.yaml
- scheduler.yaml
- builder.yaml
- terraformer.yaml
- ansibler.yaml
- kube-eleven.yaml
- kuber.yaml
- cluster-rbac
- mongo
- minio
- dynamo

# Alter ValidatingWebhookConfiguration and Certificate fields, so they will match the generated namespace
replacements:
- source:
    fieldPath: metadata.name
    kind: Namespace
  targets:
  - fieldPaths:
    - webhooks.*.namespaceSelector.matchLabels.kubernetes\.io/metadata\.name
    - webhooks.*.clientConfig.service.namespace
    select:
      kind: ValidatingWebhookConfiguration
      name: claudie-webhook
- source:
    fieldPath: metadata.name
    kind: Namespace
  targets:
  - fieldPaths:
    - metadata.annotations.cert-manager\.io/inject-ca-from
    options:
      delimiter: /
    select:
      kind: ValidatingWebhookConfiguration
      name: claudie-webhook
  - fieldPaths:
    - spec.dnsNames.*
    options:
      delimiter: .
      index: 1
    select:
      kind: Certificate
      name: claudie-webhook-certificate

configMapGenerator:
- envs:
  - .env
  name: env
  options:
    labels:
      app.kubernetes.io/part-of: claudie
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/dirtboll/claudie/ansibler
  newTag: v0.6.6
- name: ghcr.io/dirtboll/claudie/autoscaler-adapter
  newTag: v0.6.6
- name: ghcr.io/dirtboll/claudie/builder
  newTag: v0.6.6
- name: ghcr.io/dirtboll/claudie/claudie-operator
  newTag: v0.6.6
- name: ghcr.io/dirtboll/claudie/context-box
  newTag: v0.6.6
- name: ghcr.io/dirtboll/claudie/kube-eleven
  newTag: v0.6.6
- name: ghcr.io/dirtboll/claudie/kuber
  newTag: v0.6.6
- name: ghcr.io/dirtboll/claudie/scheduler
  newTag: v0.6.6
- name: ghcr.io/dirtboll/claudie/terraformer
  newTag: v0.6.6
